"""Write reports/skill_data.js (every skill per role, with 12-month change)."""

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ROLES = {
    "Software Engineering Core": "Software Engineer",
    "Data Analytics": "Data / BI Analyst",
    "AI Engineering": "AI / ML Engineer",
    "Data Engineering": "Data Engineer",
    "DevOps Engineering": "DevOps / Platform Engineer",
    "Frontend Development": "Frontend Engineer",
    "Data Science Core": "Data Scientist",
    "Product Management": "Product Manager",
    "Cybersecurity Core": "Security Engineer",
    "Data Storytelling": "Analytics Communicator",
    "AI Workflow Automation": "Automation / AI Ops Specialist",
}

df = pd.read_csv(ROOT / "data/processed/skill_diffusion.csv")
cols = ["global_share_now", "kenya_share_now", "global_trend_12m", "kenya_trend_12m"]
df[cols] = (df[cols].fillna(0) * 100).round(2)
role_trends = [
    [role, df[df.zindua_track == track].sort_values("global_share_now", ascending=False)
        [["skill", *cols]].values.tolist()]
    for track, role in ROLES.items()
]
out = ROOT / "reports/skill_data.js"
out.write_text(
    "// [skill, global%, kenya%, global 12m pp, kenya 12m pp] per role. "
    "Generated by scripts/build_dashboard_data.py\n"
    f"const roleTrends = {json.dumps(role_trends, separators=(',', ':'))};\n",
    encoding="utf-8",
)
print(f"{out}: {sum(len(s) for _, s in role_trends)} skills")
